### ISSUE TITLE
ImportError: cannot import name 'MyelinSeg' in LINUX

### ISSUE THREAD

**Issue by alzaia** [neuropoly/axonsegpy#18]
neuropoly@abbey:~/Documents/aldo_tmp/axonsegpy/axonsegpy$ '/home/neuropoly/anaconda3/bin/python' main.py
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from core import ConfigParser
  File "/home/neuropoly/Documents/aldo_tmp/axonsegpy/axonsegpy/core/__init__.py", line 3, in <module>
    from core import ConfigParser
  File "/home/neuropoly/Documents/aldo_tmp/axonsegpy/axonsegpy/core/ConfigParser.py", line 2, in <module>
    from core.RunConfig import runAlgo
  File "/home/neuropoly/Documents/aldo_tmp/axonsegpy/axonsegpy/core/RunConfig.py", line 1, in <module>
    from algo import *
  File "/home/neuropoly/Documents/aldo_tmp/axonsegpy/axonsegpy/algo/__init__.py", line 3, in <module>
    from algo import MyelinSeg
ImportError: cannot import name 'MyelinSeg'

---

neuropoly@abbey:~/Documents/aldo_tmp/axonsegpy/axonsegpy$ '/home/neuropoly/anaconda3/bin/python' main.py
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from core import ConfigParser
  File "/home/neuropoly/Documents/aldo_tmp/axonsegpy/axonsegpy/core/__init__.py", line 3, in <module>
    from core import ConfigParser
  File "/home/neuropoly/Documents/aldo_tmp/axonsegpy/axonsegpy/core/ConfigParser.py", line 2, in <module>
    from core.RunConfig import runAlgo
  File "/home/neuropoly/Documents/aldo_tmp/axonsegpy/axonsegpy/core/RunConfig.py", line 1, in <module>
    from algo import *
  File "/home/neuropoly/Documents/aldo_tmp/axonsegpy/axonsegpy/algo/__init__.py", line 3, in <module>
    from algo import MyelinSeg
ImportError: cannot import name 'MyelinSeg'

**Comment by HadrienPerrineau** [comment]
Typo Error. The file is MeylinSeg and not MyelinSeg. Our fault.
